Repository CapstoneDesignCau/Back-End, pull requests merged in 2024-10, with the labels that each got.

#11 Feat: AWS S3에 파일 업로드 및 파일 삭제 로직 구현
  src/main/java/capstone/capstone01/domain/post/controller/PostController.java
  src/main/java/capstone/capstone01/domain/storage/controller/StorageController.java
  src/main/java/capstone/capstone01/domain/storage/domain/FileSaveInfo.java
  src/main/java/capstone/capstone01/domain/storage/domain/enums/FileCategory.java
  src/main/java/capstone/capstone01/domain/storage/domain/enums/FileInfo.java
  src/main/java/capstone/capstone01/domain/storage/domain/repository/FileSaveInfoRepository.java
  src/main/java/capstone/capstone01/domain/storage/service/StorageService.java
  src/main/java/capstone/capstone01/domain/storage/service/StorageServiceImpl.java
  src/main/java/capstone/capstone01/global/apipayload/code/status/ErrorStatus.java
  src/main/java/capstone/capstone01/global/apipayload/code/status/SuccessStatus.java
  src/main/java/capstone/capstone01/global/config/AmazonConfig.java
  src/main/java/capstone/capstone01/global/config/SecurityConfig.java
  src/main/java/capstone/capstone01/global/config/SwaggerConfig.java
  src/main/java/capstone/capstone01/global/exception/security/CustomAccessDeniedHandler.java
  src/main/java/capstone/capstone01/global/exception/security/CustomAuthenticationEntryPoint.java
  src/main/java/capstone/capstone01/global/exception/specific/FileException.java
  src/main/java/capstone/capstone01/global/util/converter/StorageConverter.java
  src/main/resources/application.yml
Labels: Feat

#12 Fix: 잘못된 파일 에러 코드 수정
  src/main/java/capstone/capstone01/global/apipayload/code/status/ErrorStatus.java
Labels: fix

#20 Feat : 게시글 댓글 생성, 삭제, 조회 로직 추가
  src/main/java/capstone/capstone01/domain/comment/controller/CommentController.java
  src/main/java/capstone/capstone01/domain/comment/domain/Comment.java
  src/main/java/capstone/capstone01/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/capstone/capstone01/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/capstone/capstone01/domain/comment/service/CommentService.java
  src/main/java/capstone/capstone01/domain/comment/service/CommentServiceImpl.java
  src/main/java/capstone/capstone01/domain/imagepost/controller/ImagePostController.java
  src/main/java/capstone/capstone01/domain/imagepost/domain/ImagePost.java
  src/main/java/capstone/capstone01/domain/imagepost/dto/request/ImagePostCreateRequestDto.java
  src/main/java/capstone/capstone01/domain/imagepost/dto/response/ImagePostResponseDto.java
  src/main/java/capstone/capstone01/domain/imagepost/service/ImagePostService.java
  src/main/java/capstone/capstone01/domain/imagepost/service/ImagePostServiceImpl.java
  src/main/java/capstone/capstone01/domain/like/controller/LikeController.java
  src/main/java/capstone/capstone01/global/apipayload/code/status/ErrorStatus.java
  src/main/java/capstone/capstone01/global/apipayload/code/status/SuccessStatus.java
  src/main/java/capstone/capstone01/global/util/converter/CommentConverter.java
  src/main/java/capstone/capstone01/global/util/converter/ImagePostConverter.java
Labels: Feat

#22 Refactor: ImagePost를 Post로 변경
  src/main/java/capstone/capstone01/domain/comment/domain/Comment.java
  src/main/java/capstone/capstone01/domain/comment/service/CommentServiceImpl.java
  src/main/java/capstone/capstone01/domain/imagepost/domain/repository/ImagePostRepository.java
  src/main/java/capstone/capstone01/domain/imagepost/service/ImagePostService.java
  src/main/java/capstone/capstone01/domain/imagepost/service/ImagePostServiceImpl.java
  src/main/java/capstone/capstone01/domain/like/controller/LikeController.java
  src/main/java/capstone/capstone01/domain/like/domain/CommentLike.java
  src/main/java/capstone/capstone01/domain/like/domain/PostLike.java
  src/main/java/capstone/capstone01/domain/like/domain/repository/ImagePostLikeRepository.java
  src/main/java/capstone/capstone01/domain/like/domain/repository/PostLikeRepository.java
  src/main/java/capstone/capstone01/domain/like/service/LikeService.java
  src/main/java/capstone/capstone01/domain/like/service/LikeServiceImpl.java
  src/main/java/capstone/capstone01/domain/post/controller/PostController.java
  src/main/java/capstone/capstone01/domain/post/domain/Post.java
  src/main/java/capstone/capstone01/domain/post/domain/repository/PostRepository.java
  src/main/java/capstone/capstone01/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/capstone/capstone01/domain/post/dto/response/PostResponseDto.java
  src/main/java/capstone/capstone01/domain/post/service/PostService.java
  src/main/java/capstone/capstone01/domain/post/service/PostServiceImpl.java
  src/main/java/capstone/capstone01/global/exception/specific/PostException.java
  src/main/java/capstone/capstone01/global/util/converter/CommentConverter.java
  src/main/java/capstone/capstone01/global/util/converter/ImagePostConverter.java
  src/main/java/capstone/capstone01/global/util/converter/LikeConverter.java
  src/main/java/capstone/capstone01/global/util/converter/PostConverter.java
Labels: refactor

#28 Feat: 게시글, 댓글 관련 필요한 API들 모두 추가
  src/main/java/capstone/capstone01/domain/comment/controller/CommentController.java
  src/main/java/capstone/capstone01/domain/comment/domain/Comment.java
  src/main/java/capstone/capstone01/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/capstone/capstone01/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/capstone/capstone01/domain/comment/service/CommentService.java
  src/main/java/capstone/capstone01/domain/comment/service/CommentServiceImpl.java
  src/main/java/capstone/capstone01/domain/like/service/LikeServiceImpl.java
  src/main/java/capstone/capstone01/domain/post/controller/PostController.java
  src/main/java/capstone/capstone01/domain/post/domain/Post.java
  src/main/java/capstone/capstone01/domain/post/domain/repository/PostRepository.java
  src/main/java/capstone/capstone01/domain/post/dto/response/PostResponseDto.java
  src/main/java/capstone/capstone01/domain/post/dto/response/PostSummaryResponseDto.java
  src/main/java/capstone/capstone01/domain/post/service/PostService.java
  src/main/java/capstone/capstone01/domain/post/service/PostServiceImpl.java
  src/main/java/capstone/capstone01/domain/user/service/UserServiceImpl.java
  src/main/java/capstone/capstone01/global/util/converter/CommentConverter.java
  src/main/java/capstone/capstone01/global/util/converter/PostConverter.java
  src/main/java/capstone/capstone01/global/util/converter/UserConverter.java
  src/main/java/capstone/capstone01/global/util/value/StaticValue.java
Labels: Feat

#31 Feat: 해쉬태그 도메인 완성 및 Default Url Null 버그 해결
  src/main/java/capstone/capstone01/domain/hashtag/controller/HashtagController.java
  src/main/java/capstone/capstone01/domain/hashtag/domain/Hashtag.java
  src/main/java/capstone/capstone01/domain/hashtag/domain/repository/HashtagRepository.java
  src/main/java/capstone/capstone01/domain/hashtag/dto/request/HashtagCreateRequestDto.java
  src/main/java/capstone/capstone01/domain/hashtag/dto/request/exampleRequestDto.java
  src/main/java/capstone/capstone01/domain/hashtag/dto/response/HashtagResponseDto.java
  src/main/java/capstone/capstone01/domain/hashtag/dto/response/exampleResponseDto.java
  src/main/java/capstone/capstone01/domain/hashtag/service/HashtagService.java
  src/main/java/capstone/capstone01/domain/hashtag/service/HashtagServiceImpl.java
  src/main/java/capstone/capstone01/domain/hashtag/service/hashtagService.java
  src/main/java/capstone/capstone01/global/apipayload/code/status/SuccessStatus.java
  src/main/java/capstone/capstone01/global/util/converter/HashtagConverter.java
  src/main/java/capstone/capstone01/global/util/converter/UserConverter.java
  src/main/java/capstone/capstone01/global/util/value/StaticValue.java
Labels: bug, Feat
